# secrets management via .env (excluded via .gitignore)
dotenv: .env

# brownie default values made explicit
compiler:
    evm_version: null
    solc:
        # 0.8.2 doesn't work with chainlink operator (needs ^0.7.0)
        # version: 0.7.6
        version: 0.8.2
        optimizer:
            enabled: true
            runs: 200
        # https://eth-brownie.readthedocs.io/en/stable/compile.html#compiler-settings
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0"
            - "@chainlink=smartcontractkit/chainlink@1.6.0"

# packages below will be added to brownie
# you may use 'brownie pm list' after 'brownie compile' 
# to list the packages installed via the dependency list below
dependencies:
    # **Important**: If you update any version here, please also update them in .vscode/settings.json section 'solidity.remappingsUnix'
    # github dependency format: <owner>/<repository>@<release>
    - OpenZeppelin/openzeppelin-contracts@4.7.0
    - smartcontractkit/chainlink@1.6.0
