FROM python:3.9-bullseye

ENV NODE_VERISON 16
ENV NVM_DIR /github/home/.nvm
SHELL ["/bin/bash", "-c"]

WORKDIR /github/home
ENV HOME /github/home

# install node 16 via nvm
RUN mkdir -p ${NVM_DIR} \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERISON \
    && nvm alias default $NODE_VERSION \
    && nvm use default 

COPY prepare_environment.sh .
RUN ./prepare_environment.sh

COPY .bashrc .
