name: Build container

on: 
  push:
    branches: 
    - '*'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@v2.x
      - name: Login to registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u etherisc --password-stdin

      - name: Build container
        run: docker build -t ghcr.io/etherisc/gif-brownie-container:${{ env.GITHUB_REF_SLUG }} .
      - name: Publish container
        run: docker push ghcr.io/etherisc/gif-brownie-container:${{ env.GITHUB_REF_SLUG }}

      - name: Build container for devconainer
        run: docker build -f Dockerfile.devcontainer -t ghcr.io/etherisc/gif-brownie-devcontainer:${{ env.GITHUB_REF_SLUG }} .
      - name: Publish container for devcontainer
        run: docker push ghcr.io/etherisc/gif-brownie-devcontainer:${{ env.GITHUB_REF_SLUG }}
